import cx_Oracle
import pandas as pd
import os
from datetime import datetime

def create_connection():
    """Create connection to Oracle database"""
    try:
        # Oracle connection parameters
        username = "system"  # default Oracle XE username
        password = "oracle"  # default Oracle XE password
        dsn = "localhost:1521/XE"  # default Oracle XE connection string
        
        # Create connection
        connection = cx_Oracle.connect(username, password, dsn)
        print("Successfully connected to Oracle Database")
        return connection
    except cx_Oracle.Error as error:
        print(f"Error connecting to Oracle Database: {error}")
        return None

def create_tables(connection):
    """Create necessary tables in the database"""
    try:
        cursor = connection.cursor()
        
        # Create Banks table
        cursor.execute("""
        CREATE TABLE banks (
            bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_name VARCHAR2(100) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)
        
        # Create Reviews table
        cursor.execute("""
        CREATE TABLE reviews (
            review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_id NUMBER,
            review_text CLOB,
            rating NUMBER(2),
            review_date DATE,
            source VARCHAR2(50),
            sentiment_score NUMBER(3,2),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (bank_id) REFERENCES banks(bank_id)
        )
        """)
        
        connection.commit()
        print("Tables created successfully")
    except cx_Oracle.Error as error:
        print(f"Error creating tables: {error}")
        connection.rollback()

def insert_data(connection, csv_file):
    """Insert data from CSV into the database"""
    try:
        # Read the CSV file
        df = pd.read_csv(csv_file)
        
        cursor = connection.cursor()
        
        # Insert unique banks first
        unique_banks = df['bank'].unique()
        bank_ids = {}
        
        for bank in unique_banks:
            cursor.execute("""
            INSERT INTO banks (bank_name)
            VALUES (:1)
            RETURNING bank_id INTO :2
            """, (bank, cursor.var(cx_Oracle.NUMBER)))
            bank_ids[bank] = cursor.var.getvalue()
        
        # Insert reviews
        for _, row in df.iterrows():
            cursor.execute("""
            INSERT INTO reviews (
                bank_id, review_text, rating, review_date, 
                source, sentiment_score
            )
            VALUES (
                :1, :2, :3, :4, :5, :6
            )
            """, (
                bank_ids[row['bank']],
                row['review'],
                row['rating'],
                pd.to_datetime(row['date']).date(),
                row['source'],
                row.get('sentiment', 0)  # Use 0 if sentiment not available
            ))
        
        connection.commit()
        print(f"Successfully inserted {len(df)} reviews")
        
    except cx_Oracle.Error as error:
        print(f"Error inserting data: {error}")
        connection.rollback()
    except Exception as error:
        print(f"Error processing data: {error}")
        connection.rollback()

def export_schema(connection):
    """Export database schema to SQL file"""
    try:
        cursor = connection.cursor()
        
        # Get table creation scripts
        cursor.execute("""
        SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
        FROM user_tables
        WHERE table_name IN ('BANKS', 'REVIEWS')
        """)
        
        schema_scripts = cursor.fetchall()
        
        # Write to file
        with open('task4/database_schema.sql', 'w') as f:
            f.write("-- Database Schema for Bank Reviews\n")
            f.write("-- Generated on: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "\n\n")
            for script in schema_scripts:
                f.write(script[0].read() + "\n\n")
        
        print("Schema exported successfully to database_schema.sql")
        
    except cx_Oracle.Error as error:
        print(f"Error exporting schema: {error}")

def main():
    # Create connection
    connection = create_connection()
    if not connection:
        return
    
    try:
        # Create tables
        create_tables(connection)
        
        # Insert data
        insert_data(connection, '../cleaned_reviews.csv')
        
        # Export schema
        export_schema(connection)
        
    finally:
        # Close connection
        connection.close()
        print("Database connection closed")

if __name__ == "__main__":
    main() 